import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import '@rainbow-me/rainbowkit/styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers >
            {children}
        </Providers>
      </body>
    </html>
  )
}
